// access token
export const ACCESS_TOKEN_LOADING = "ACCESS_TOKEN_LOADING" 
export const ACCESS_TOKEN_FAILED = "ACCESS_TOKEN_FAILED" 
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS"

// auth
export const AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING" 
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED" 
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS" 


// fis
export const FI_LOADING = "FI_LOADING" 
export const FI_FAILED = "FI_FAILED" 
export const FI_SUCCESS = "FI_SUCCESS" 

// Account Types
export const ACCOUNT_TYPES_LOADING = "ACCOUNT_TYPES_LOADING" 
export const ACCOUNT_TYPES_FAILED = "ACCOUNT_TYPES_FAILED" 
export const ACCOUNT_TYPES_SUCCESS = "ACCOUNT_TYPES_SUCCESS" 

// fis
export const BANK_PROFILE_LOADING = "BANK_PROFILE_LOADING" 
export const BANK_PROFILE_FAILED = "BANK_PROFILE_FAILED" 
export const BANK_PROFILE_SUCCESS = "BANK_PROFILE_SUCCESS" 


export const ACTIVE_BANK_LOADING = "ACTIVE_BANK_LOADING" 
export const ACTIVE_BANK_FAILED = "ACTIVE_BANK_FAILED" 
export const ACTIVE_BANK_SUCCESS = "ACTIVE_BANK_SUCCESS" 


export const BENEFICIARIES_LOADING = "BENEFICIARIES_LOADING" 
export const BENEFICIARIES_FAILED = "BENEFICIARIES_FAILED" 
export const BENEFICIARIES_SUCCESS = "BENEFICIARIES_SUCCESS" 

// billers
export const BILLERS_LOADING = "BILLERS_LOADING" 
export const BILLERS_FAILED = "BILLERS_FAILED" 
export const BILLERS_SUCCESS = "BILLERS_SUCCESS" 
export const AIRTIME_LOADING = "AIRTIME_LOADING" 
export const AIRTIME_FAILED = "AIRTIME_FAILED" 
export const AIRTIME_SUCCESS = "AIRTIME_SUCCESS" 